name: Build ValleyCast

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'  # Targeting .NET 6.0

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Publish mod
      run: dotnet publish --configuration Release --output ./ModOutput

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: stardew-mod-build
        path: ./ModOutput/
