name: Build ValleyCast

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests (if you have any)
        run: dotnet test --no-build --verbosity normal --configuration Release

      - name: Publish the mod (optional)
        run: dotnet publish --configuration Release --output ./output

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: stardew-mod-build
          path: ./output/
