name: Build Stardew Valley Mod

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore ValleyCast/ValleyCast.csproj

    - name: Copy necessary assemblies
      run: |
        mkdir -p ModProject/Assemblies
        cp .github/Assemblies/* ModProject/Assemblies/

    - name: Build the project
      run: dotnet build ValleyCast/ValleyCast.csproj --configuration Release --no-restore

    - name: Publish build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ModBuild
        path: |
          ModProject/bin/Release/net6.0/
